---
- name: Deploy Monitoring Stack
  hosts: monitoring_servers
  become: true
  vars:
    monitoring:
      logging:
        enabled: true
      metrics:
        enabled: true
      network:
        enabled: true

  roles:
    # Logging Stack
    - role: minio  # Object storage for logs
      tags: ['minio', 'logging']
      when: monitoring.logging.enabled | bool

    - role: loki  # Log aggregation
      tags: ['loki', 'logging']
      when: monitoring.logging.enabled | bool

    - role: promtail  # Log shipping
      tags: ['promtail', 'logging']
      when: monitoring.logging.enabled | bool

    # Metrics Stack
    - role: netdata  # System metrics
      tags: ['netdata', 'metrics']
      when: monitoring.metrics.enabled | bool

    - role: glances  # System monitoring
      tags: ['glances', 'metrics']
      when: monitoring.metrics.enabled | bool

    - role: stats    # Additional system stats
      tags: ['stats', 'metrics']
      when: monitoring.metrics.enabled | bool

    # Network Monitoring
    - role: speedtest-tracker
      tags: ['speedtest', 'network']
      when: monitoring.network.enabled | bool

    - role: wireshark
      tags: ['wireshark', 'network']
      when: monitoring.network.enabled | bool
