# Global config
global:
  scrape_interval: 15s  # Set the scrape interval to every 15 seconds
  evaluation_interval: 15s  # Evaluate rules every 15 seconds
  # scrape_timeout is set to the global default (10s).

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node"
    static_configs:
      - targets: ["stats-node-exporter:9100"]

  - job_name: "telegraf"
    static_configs:
      - targets: ["stats-telegraf:9273"]

  - job_name: "smartctl"
    static_configs:
      - targets: ["stats-smartctl:9633"]

  - job_name: "speedtest"
    scrape_interval: 30m
    scrape_timeout: 5m
    static_configs:
      - targets: ["stats-speedtest:9798"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["stats-cadvisor:8080"]
    metrics_path: /metrics
    scrape_interval: 15s
